[project]
name = "aoc-2025"
version = "0.1.0"
description = "An attempt to solve all 12 puzzles from 2025s Advent of Code."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.5",
]
